[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { workspace = true }
dirs = { workspace = true }
strum = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }