[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt update",
    "apt install -y clang"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt update",
    "apt install -y clang"
]

[target.powerpc64le-unknown-linux-gnu]
pre-build = [
    "apt update",
    "apt install -y clang"
]
