[package]
name = "gfold"
version = "4.3.3"
edition = "2021"

authors = ["Nick Gerace <nickagerace@gmail.com>"]
categories = ["command-line-utilities", "command-line-interface"]
description = "CLI tool to help keep track of your Git repositories."
homepage = "https://nickgerace.dev"
keywords = ["git", "cli"]
license = "Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/nickgerace/gfold/"

[dependencies]
libgfold = { path = "../../lib/libgfold" }

anyhow = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }

env_logger = { version = "0.10", features = ["humantime"], default_features = false }
serde_json = "1.0"
toml = "0.7"
