[package]
name = "gfold"
version = "4.3.3"
edition = "2021"

authors = ["Nick Gerace <nickagerace@gmail.com>"]
categories = ["command-line-utilities", "command-line-interface"]
description = "CLI tool to help keep track of your Git repositories."
homepage = "https://nickgerace.dev"
keywords = ["git", "cli"]
license = "Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/nickgerace/gfold/"

[dependencies]
libgfold = { version = "0.1.1", path = "../../lib/libgfold" }

anyhow = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
