[package]
name = "gfold"
version = "4.4.1"

categories = ["command-line-utilities", "command-line-interface"]
description = "CLI tool to help keep track of your Git repositories."
keywords = ["git", "cli"]
readme = "../../README.md"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libgfold = { version = "0.1.2", path = "../../lib/libgfold" }

anyhow = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
