name: release
on:
  push:
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  release:
    name: "Release"
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          # Linux
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            asset_name: gfold-linux-gnu-aarch64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            asset_name: gfold-linux-gnu-x86-64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            asset_name: gfold-linux-musl-x86-64
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            asset_name: gfold-linux-musl-aarch64
          - target: powerpc64le-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            asset_name: gfold-linux-gnu-powerpc64le
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            asset_name: gfold-windows-x86-64.exe
          # macOS
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: gfold-darwin-aarch64
          - target: x86_64-apple-darwin
            os: macos-13
            asset_name: gfold-darwin-x86-64

    env:
      CARGO: cargo

    steps:
      - uses: actions/checkout@v4

      - name: Set up cross compiling
        if: matrix.job.cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Configure cross compiling
        if: matrix.job.cross
        run: echo "CARGO=cross" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Build
        run: $CARGO build --release --locked --target ${{ matrix.job.target }}

      - shell: bash
        run: |
          if [ $(echo ${{ github.ref }} | grep "rc") ]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "PRERELEASE=true"
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
            echo "PRERELEASE=false"
          fi
          echo $PRERELEASE

          mv target/${{ matrix.job.target }}/release/gfold${{ startsWith(matrix.job.os, 'windows-') && '.exe' || '' }} ${{ matrix.job.asset_name }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.job.asset_name }}
          prerelease: ${{ env.PRERELEASE }}
          body: "Please refer to **[CHANGELOG.md](https://github.com/nickgerace/gfold/blob/main/CHANGELOG.md)** for information on this release."
