on:
  push:
    tags: ['*']
name: release
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gfold
            asset_name: gfold-linux-gnu-amd64
          - os: windows-latest
            artifact_name: gfold.exe
            asset_name: gfold-windows-amd64
          - os: macos-latest
            artifact_name: gfold
            asset_name: gfold-darwin-amd64
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
