name: release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: "Release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gfold
            asset_name: gfold-linux-gnu-amd64
          - os: windows-latest
            artifact_name: gfold.exe
            asset_name: gfold-windows-amd64.exe
          - os: macos-latest
            artifact_name: gfold
            asset_name: gfold-darwin-amd64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo build --release --locked
      - shell: bash
        run: |
          if [ $(echo ${{ github.ref }} | grep "rc") ]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
            echo "PRERELEASE=true"
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
            echo "PRERELEASE=false"
          fi
          echo $PRERELEASE

          mv target/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
          prerelease: ${{ env.PRERELEASE }}
          body: "Please refer to **[CHANGELOG.md](https://github.com/nickgerace/gfold/blob/main/CHANGELOG.md)** for information on this release."
